version: "3.9"

services:
  app:
    build:
      context: .
      args:
       - DEV=true
    ports:
     - "9000:9000"
    volumes:
     - ./app:/app # Sync Django code
     - ./chroma_stores:/app/chroma_stores
     - ./app/uploads:/app/uploads # Uploads
    command: >
      sh -c "python manage.py wait_for_db && 
        python manage.py migrate &&
        python manage.py runserver  0.0.0.0:9000"
    environment:
      - DB_HOST=db
      - DB_NAME=vaultqdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data # Sets up a volume to persist database data
    environment:
      - POSTGRES_DB=vaultqdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

volumes:
  postgres-data:
