# Generated by Django 5.2.1 on 2025-06-09 20:14

import django.db.models.deletion
import project.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                help_text="Name of the project", max_length=255, unique=True
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Original File Name", max_length=255),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded document file",
                        upload_to=project.models.document_upload_path,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "content_type",
                    models.CharField(help_text="MIME type of the file", max_length=100),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current processing status",
                        max_length=200,
                    ),
                ),
                (
                    "chunks_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of chunks created from this document",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this document belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="project.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded the document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
