# Generated by Django 5.2.1 on 2025-06-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_alter_project_name_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="chunks_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of chunks created from this document",
                null=True,
            ),
        ),
    ]
